name: Build Standalone Python application

on:
  push:
    branches: [ "automation-test" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    steps:
      - name: Create Standalone App
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: '.github/Exquis Remapper.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: ${{ matrix.os }}-Exquis-Isomorphic-Remapper'
          compression_level: 9
          #options: --onefile, --name "Exquis Remapper", --windowed, 
