name: Build Standalone Python application

on:
  push:
    branches: [ "automation-test" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: <windows-latest / ubuntu-latest / macos-latest>
    steps:
      - name: Create Standalone App
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'app.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Exquis Isomorphic Remapper'
          options: --onefile, --name "Exquis Remapper", --windowed, 
