name: Build Standalone Python application

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Create Standalone App
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'Exquis Remapper.spec'
          requirements: 'requirements.txt'
          #upload_exe_with_name: ${{ matrix.os }}-Exquis-Isomorphic-Remapper-${{github.ref_name}}
          #compression_level: 9
          #options: --onefile, --name "Exquis Remapper", --windowed,
      - name: Create zip for upload
        uses: vimtor/action-zip@v1.2
        with:
          files: ./dist/
          dest: Exquis-Isomorphic-Remapper-${{ matrix.os }}-${{github.ref_name}}.zip
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: Exquis-Isomorphic-Remapper-${{ matrix.os }}-${{github.ref_name}}.zip
